from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field

class AppState(BaseModel):
    """
    The state of the application, managed by Pydantic for type safety and validation.
    """
    user_request: str = Field(description="The initial request from the user.")
    
    plan: Optional[Dict[str, Any]] = Field(default=None, description="The execution plan generated by the planning agent.")
    
    perception_data: Optional[Dict[str, Any]] = Field(default=None, description="Data collected by the perception agent.")
    
    market_commentary: Optional[str] = Field(default=None, description="Market commentary generated by the decision agent.")
    
    features_for_forecasting: Optional[List[str]] = Field(default=None, description="Features selected for the forecasting model.")

    feature_selection_report: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "决策智能体的完整评审记录：每个候选特征的三个维度得分、理由、"
            "检索到的证据出处、重试轮数。保留它是为了让'为什么选了这个特征'"
            "可以被追溯，而不是只留一个结论。"
        ),
    )

    forecast_result: Optional[Dict[str, Any]] = Field(default=None, description="The final forecast result.")

    # New fields for dynamic workflow control
    next_step: Optional[str] = Field(default=None, description="The next agent to execute.")
    error_message: Optional[str] = Field(default=None, description="Any error message that occurred.")